name: main

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ci-key-file:
          # absolute
          - ${{ github.workspace }}/test/fixtures/key

          # relative
          - test/fixtures/key
        sops-file:
          # absolute
          - ${{ github.workspace }}/test/fixtures/test.sops.yaml

          # relative
          - test/fixtures/test.sops.yaml

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: Setup gha cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false

      - name: Run install action
        uses: ./.
        with:
          ci-key-file: ${{ matrix.ci-key-file }}
          sops-file: ${{ matrix.sops-file }}

      - name: Test
        run: test/main.py
